WITH RESUMO_PEDIDOS AS (
    SELECT
        P.CLIENTE_ID,
        COUNT(P.ID) AS TOTAL_PEDIDOS,
        SUM(P.VALOR_TOTAL) AS VALOR_TOTAL_COMPRAS,
        MAX(P.DATA_PEDIDO) AS ULTIMA_COMPRA
    FROM PEDIDOS P
    WHERE P.STATUS = 'F'
    GROUP BY P.CLIENTE_ID
)
SELECT
    C.ID AS CLIENTE_ID,
    C.NOME,
    C.EMAIL,
    C.CIDADE,
    C.DATA_CADASTRO,
    COALESCE(RP.TOTAL_PEDIDOS, 0) AS TOTAL_PEDIDOS,
    COALESCE(RP.VALOR_TOTAL_COMPRAS, 0) AS VALOR_TOTAL_COMPRAS,
    RP.ULTIMA_COMPRA,
    CASE
        WHEN RP.ULTIMA_COMPRA IS NULL THEN 'NUNCA COMPROU'
        WHEN RP.ULTIMA_COMPRA < DATEADD(-180 DAY TO CURRENT_DATE)
            THEN 'INATIVO'
        ELSE 'ATIVO'
    END AS CLASSIFICACAO
FROM CLIENTES C
LEFT JOIN RESUMO_PEDIDOS RP
    ON RP.CLIENTE_ID = C.ID
WHERE C.ATIVO = 'S'
  AND (
        :NOME IS NULL
        OR UPPER(C.NOME) CONTAINING UPPER(:NOME)
      )
  AND (
        :CIDADE IS NULL
        OR UPPER(C.CIDADE) = UPPER(:CIDADE)
      )
ORDER BY
    CASE
        WHEN RP.ULTIMA_COMPRA IS NULL THEN 1
        ELSE 0
    END,
    RP.ULTIMA_COMPRA DESC,
    C.NOME;